
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_redshift_demo'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_redshift_demo'

vars:
  categoria_id: 9

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"


on-run-start: "{{ dbt_ejecucion_inicial('inicio_ejecucion') }}"
on-run-end: "{{ dbt_ejecucion_inicial('fin_ejecucion') }}"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models


models:
  dbt_redshift_demo:
    # Config indicated by + and applies to all files under models/dbt_staging/
    dbt_staging:
      +materialized: view
      +schema: dbt_staging
    dbt_source_redshift:
      +materialized: table
      +schema: dbt_source_redshift
      +pre-hook: "{{ dbt_ejecucion_modelo(this,'inicio_ejecucion','cantidad_registros') }}"
      +post-hook: "{{ dbt_ejecucion_modelo(this,'fin_ejecucion','cantidad_registros') }}"
      +tags: 
        - src_rs
